### ISSUE TITLE
CPH2451 images

### ISSUE THREAD

**Issue by asheroto** [luk1337/oplus_archive#1]
Hello! I used your archive several times working with my OnePlus 9 Pro.

I have a OnePlus 11 now, CPH2451, and I don't see any of those ROMs listed.

I couldn't find any, but did make a post on xda-developers.

I did find this:
https://mega.nz/file/1WwmmDgY#cpgsJ_Vk0gIMCoTXoqzEygNxh5h80uvwG1Az-wMzrcs

And downloaded it, which looks like this...
![image](https://github.com/luk1337/oplus_archive/assets/49938263/3634ac1d-6c63-42ad-a4d7-4e9f4902278f)

![image](https://github.com/luk1337/oplus_archive/assets/49938263/d73a4587-2323-462c-8ada-ff98097ced48)

So that might be it, but haven't confirmed?

**Comment by luk1337** [comment]
This archive is mostly to serve as blobs source for LineageOS devices that I have something to do with, and since I have nothing to do with OnePlus 11, I don't have anything for it. You might want to look at Oxygen Updater, maybe they have some links for you.

**Comment by asheroto** [comment]
Ah okay, I just found this repo on an article somewhere and was thinking it was for most OP devices.

I did try Oxygen Updater but no full option for CPH2451.

Thanks for your help!
